### ISSUE TITLE
Overriding Serializer Breaks Existing Data

### ISSUE THREAD

**Issue by LeoAdamek** [dunglas/doctrine-json-odm#115]
Overriding the serializer to enable the DateTime normalizer as per the [FAQ](https://github.com/dunglas/doctrine-json-odm#faq) breaks all existing data. This is the case even if the overridden serializer contains the exact [configuration of the serializer provided by the bundle](https://github.com/dunglas/doctrine-json-odm/blob/main/src/Bundle/Resources/config/services.xml#L18-L26)

```yaml
    dunglas_doctrine_json_odm.serializer:
        class: Dunglas\DoctrineJsonOdm\Serializer
        arguments:
          - - '@dunglas_doctrine_json_odm.normalizer.array'
            - '@dunglas_doctrine_json_odm.normalizer.object'
          - - '@serializer.encoder.json'
        public: true
```

New values stored no longer have a `#type` marking, and existing values loaded do not load correctly, loading in instead as `stdClass` objects instead of objects hydrated to the class marked by `#type`

Has anyone else had and resolved this problem?

Environment:

PHP 8.1.4
Symfony 5.4
JSON ODM 1.1
