### ISSUE TITLE
Bad Normalization of DateTime and DateTimeZone

### ISSUE THREAD

**Issue by mgiraud** [dunglas/doctrine-json-odm#19]
The Normalization of Datetimezone and Datetimedoes not work well since the extracted attributes do not match the real attribute name.
Example for Datetime zone :
The object looks like
```
DateTimeZone {#857 ▼
  +"timezone_type": 3
  +"timezone": "UTC"
}
```
where the methods are 
-  public array getLocation ( void )
- public string getName ( void )
- public int getOffset ( DateTime $datetime )

The raised exception is : Cannot create an instance of DateTimeZone from serialized data because its constructor requires parameter "timezone" to be present.

Is there a way to fix this ?

**Comment by dunglas** [comment]
This can fixed by registering the Symfony's `DateTimeNormalizer`.

**Comment by Dragonqos** [comment]
Hey) I have the same issue. Can you place an example how to resolve this issue with DateTimeNormalizer please?

**Comment by jschroed91** [comment]
@Dragonqos If you're using Symfony, you can register the `DateTimeNormalizer` by registering it as a service and tagging it with `serializer.normalizer`.

For example:

```yaml
services:
    # ...
    datetime_normalizer:
        class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }
```

Or you're instantiating the Serializer object directly instead of getting the serializer from the service container, you can just pass an instance of `DateTimeNormalizer` in the first argument of the Serializer constructor:

```php
$serializer = new Serializer(array(new DateTimeNormalizer()));
```

Some additional examples can be found here: http://symfony.com/blog/new-in-symfony-3-1-datetime-normalizer
